### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by wootwoot1234**
Changing the dependencies to peerDependencies and give it a range to fix this bug: https://github.com/facebook/react-native/issues/1606

### CODE REVIEW

**Comment by cgarvis** [comment]
+1

**Comment by leejms** [comment]
+2

**Comment by srounce** [comment]
+3

**Comment by GertjanReynaert** [comment]
@wootwoot1234  Thx for making me aware of this issue, and for proposing a solution.

Closing in favor of https://github.com/GertjanReynaert/react-native-device/pull/9

**Pull request closed without merging**
